import { Injectable } from '@nestjs/common';
import * as ExcelJS from 'exceljs';
import { BaseGenerator, GenerationContext, GeneratorResult } from './base.generator';
import { opLabel } from './format.util';
import type { ColumnConfig } from 'src/common/types/report.types';

/**
 * Excel generator (ExcelJS). Produces:
 *  - a Summary sheet with styled metric cells + named ranges
 *  - a Data sheet with typed columns, auto-filter, frozen header, conditional
 *    formatting on numeric columns, and a formula total row
 */
@Injectable()
export class ExcelGenerator extends BaseGenerator {
  readonly format = 'xlsx' as const;

  async generate(ctx: GenerationContext): Promise<GeneratorResult> {
    const wb = new ExcelJS.Workbook();
    wb.creator = ctx.meta.companyName;
    wb.created = ctx.meta.generatedAt;

    this.buildSummarySheet(wb, ctx);
    this.buildDataSheet(wb, ctx);

    const arrayBuffer = await wb.xlsx.writeBuffer();
    return {
      buffer: Buffer.from(arrayBuffer),
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      extension: 'xlsx',
    };
  }

  private buildSummarySheet(wb: ExcelJS.Workbook, ctx: GenerationContext): void {
    const ws = wb.addWorksheet('Summary');
    ws.columns = [{ width: 30 }, { width: 22 }];

    ws.mergeCells('A1:B1');
    const title = ws.getCell('A1');
    title.value = ctx.layout.title;
    title.font = { size: 16, bold: true, color: { argb: 'FF1F2937' } };

    if (ctx.layout.subtitle) {
      ws.mergeCells('A2:B2');
      ws.getCell('A2').value = ctx.layout.subtitle;
      ws.getCell('A2').font = { italic: true, color: { argb: 'FF6B7280' } };
    }

    ws.getCell('A4').value = 'Generated by';
    ws.getCell('B4').value = ctx.meta.generatedBy;
    ws.getCell('A5').value = 'Generated at';
    ws.getCell('B5').value = ctx.meta.generatedAt.toISOString();
    ws.getCell('A6').value = 'Rows';
    ws.getCell('B6').value = ctx.dataset.rowCount;

    let row = 8;
    ws.getCell(`A${row}`).value = 'Key Metrics';
    ws.getCell(`A${row}`).font = { bold: true, size: 13 };
    row += 1;

    for (const s of ctx.dataset.summary) {
      const labelCell = ws.getCell(`A${row}`);
      const valueCell = ws.getCell(`B${row}`);
      labelCell.value = `${s.label} (${opLabel(s.op)})`;
      labelCell.font = { bold: true };
      valueCell.value = s.value;
      valueCell.numFmt = numFmtFor(s.format);
      valueCell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFEFF6FF' },
      };
      // Named range for each metric, e.g. Metric_Total_Revenue
      const safe = s.label.replace(/[^A-Za-z0-9]/g, '_');
      wb.definedNames.add(`Summary!$B$${row}`, `Metric_${safe}`);
      row += 1;
    }
  }

  private buildDataSheet(wb: ExcelJS.Workbook, ctx: GenerationContext): void {
    const ws = wb.addWorksheet('Data');
    const columns = ctx.layout.columns;
    const rows = this.sortRows(ctx);

    ws.columns = columns.map((c) => ({
      header: c.header,
      key: c.field,
      width: colWidth(c, rows),
      style: { numFmt: numFmtFor(c.format) },
    }));

    // Header styling
    const headerRow = ws.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2563EB' } };
    headerRow.alignment = { vertical: 'middle' };
    headerRow.height = 20;

    for (const row of rows) {
      const values: Record<string, unknown> = {};
      for (const c of columns) values[c.field] = castCell(row[c.field], c);
      ws.addRow(values);
    }

    // Freeze header + auto filter
    ws.views = [{ state: 'frozen', ySplit: 1 }];
    ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: columns.length } };

    // Formula total row for numeric/currency columns
    const lastDataRow = rows.length + 1;
    const totalRowIndex = lastDataRow + 1;
    const totalRow = ws.getRow(totalRowIndex);
    totalRow.getCell(1).value = 'Total';
    totalRow.getCell(1).font = { bold: true };
    columns.forEach((c, i) => {
      if (rows.length && (c.format === 'number' || c.format === 'currency')) {
        const col = colLetter(i + 1);
        const cell = totalRow.getCell(i + 1);
        cell.value = { formula: `SUM(${col}2:${col}${lastDataRow})` } as ExcelJS.CellFormulaValue;
        cell.numFmt = numFmtFor(c.format);
        cell.font = { bold: true };
      }
    });

    // Conditional formatting (color scale) on numeric columns
    columns.forEach((c, i) => {
      if (rows.length && (c.format === 'number' || c.format === 'currency')) {
        const col = colLetter(i + 1);
        ws.addConditionalFormatting({
          ref: `${col}2:${col}${lastDataRow}`,
          rules: [
            {
              type: 'colorScale',
              priority: 1,
              cfvo: [
                { type: 'min' },
                { type: 'percentile', value: 50 },
                { type: 'max' },
              ],
              color: [
                { argb: 'FFF8696B' },
                { argb: 'FFFFEB84' },
                { argb: 'FF63BE7B' },
              ],
            } as ExcelJS.ConditionalFormattingRule,
          ],
        });
      }
    });
  }
}

function castCell(value: unknown, col: ColumnConfig): unknown {
  if (value === null || value === undefined) return null;
  if (col.format === 'number' || col.format === 'currency' || col.format === 'percent') {
    const n = Number(value);
    return Number.isFinite(n) ? n : value;
  }
  if (col.format === 'date') {
    const d = new Date(value as string);
    return Number.isNaN(d.getTime()) ? value : d;
  }
  return value;
}

function numFmtFor(format?: string): string {
  switch (format) {
    case 'currency':
      return '$#,##0.00';
    case 'number':
      return '#,##0.##';
    case 'percent':
      return '0.00"%"';
    case 'date':
      return 'yyyy-mm-dd';
    default:
      return '@';
  }
}

function colWidth(col: ColumnConfig, rows: any[]): number {
  if (col.width) return Math.max(10, Math.round(col.width / 7));
  const maxContent = rows.reduce((max, r) => {
    const len = String(r[col.field] ?? '').length;
    return Math.max(max, len);
  }, col.header.length);
  return Math.min(50, Math.max(10, maxContent + 2));
}

function colLetter(n: number): string {
  let s = '';
  while (n > 0) {
    const m = (n - 1) % 26;
    s = String.fromCharCode(65 + m) + s;
    n = Math.floor((n - 1) / 26);
  }
  return s;
}
