import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { existsSync } from 'fs';
import { BaseGenerator, GenerationContext, GeneratorResult } from './base.generator';
import { formatValue } from './format.util';
import { renderChartPng } from './chart.util';
import type { ColumnConfig } from 'src/common/types/report.types';

const COLORS = {
  primary: '#2563eb',
  headerText: '#ffffff',
  rowAlt: '#f1f5f9',
  border: '#e2e8f0',
  text: '#1f2937',
  muted: '#6b7280',
  cardBg: '#eff6ff',
};

/**
 * PDF generator (PDFKit). Cover page, summary cards, embedded chart, and a
 * paginated data table with repeated headers, alternating rows, and a
 * "Page X of Y" footer with a generated timestamp.
 */
@Injectable()
export class PdfGenerator extends BaseGenerator {
  readonly format = 'pdf' as const;

  async generate(ctx: GenerationContext): Promise<GeneratorResult> {
    const landscape = ctx.layout.orientation === 'landscape';
    const doc = new PDFDocument({
      size: 'A4',
      layout: landscape ? 'landscape' : 'portrait',
      margins: { top: 50, bottom: 60, left: 40, right: 40 },
      bufferPages: true,
      autoFirstPage: true,
    });

    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    const done = new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });

    this.renderCover(doc, ctx);
    this.renderSummaryCards(doc, ctx);
    await this.renderChart(doc, ctx);
    this.renderTable(doc, ctx);
    this.renderFooters(doc, ctx);

    doc.end();
    const buffer = await done;
    return { buffer, contentType: 'application/pdf', extension: 'pdf' };
  }

  private renderCover(doc: PDFKit.PDFDocument, ctx: GenerationContext): void {
    const { width } = doc.page;
    const centerX = doc.page.margins.left;
    const usable = width - doc.page.margins.left - doc.page.margins.right;

    doc.moveDown(3);

    if (ctx.meta.companyLogoPath && existsSync(ctx.meta.companyLogoPath)) {
      try {
        doc.image(ctx.meta.companyLogoPath, centerX, doc.y, { width: 120 });
        doc.moveDown(2);
      } catch {
        /* ignore bad logo */
      }
    } else {
      doc
        .fontSize(14)
        .fillColor(COLORS.muted)
        .text(ctx.meta.companyName, centerX, doc.y, { width: usable, align: 'center' });
      doc.moveDown(2);
    }

    doc
      .fontSize(28)
      .fillColor(COLORS.text)
      .text(ctx.layout.title, centerX, doc.y, { width: usable, align: 'center' });

    if (ctx.layout.subtitle) {
      doc
        .moveDown(0.5)
        .fontSize(14)
        .fillColor(COLORS.muted)
        .text(ctx.layout.subtitle, { width: usable, align: 'center' });
    }

    doc.moveDown(3);
    const paramLines = Object.entries(ctx.parameters)
      .map(([k, v]) => `${k}: ${formatParam(v)}`)
      .join('    ·    ');

    doc
      .fontSize(11)
      .fillColor(COLORS.muted)
      .text(paramLines || 'No parameters', { width: usable, align: 'center' });

    doc.moveDown(1);
    doc
      .fontSize(10)
      .fillColor(COLORS.muted)
      .text(`Generated by ${ctx.meta.generatedBy}`, { width: usable, align: 'center' })
      .text(`Generated at ${ctx.meta.generatedAt.toISOString()}`, {
        width: usable,
        align: 'center',
      })
      .text(`${ctx.dataset.rowCount} rows`, { width: usable, align: 'center' });
  }

  private renderSummaryCards(doc: PDFKit.PDFDocument, ctx: GenerationContext): void {
    if (!ctx.dataset.summary.length) return;
    doc.addPage();
    const { margins } = doc.page;
    const usable = doc.page.width - margins.left - margins.right;

    doc.fontSize(16).fillColor(COLORS.text).text('Summary', margins.left, margins.top);
    doc.moveDown(0.5);

    const cards = ctx.dataset.summary;
    const perRow = Math.min(3, cards.length);
    const gap = 12;
    const cardW = (usable - gap * (perRow - 1)) / perRow;
    const cardH = 70;
    let x = margins.left;
    let y = doc.y + 5;

    cards.forEach((s, i) => {
      if (i > 0 && i % perRow === 0) {
        x = margins.left;
        y += cardH + gap;
      }
      doc.roundedRect(x, y, cardW, cardH, 6).fill(COLORS.cardBg);
      doc
        .fillColor(COLORS.muted)
        .fontSize(10)
        .text(s.label.toUpperCase(), x + 12, y + 12, { width: cardW - 24 });
      doc
        .fillColor(COLORS.primary)
        .fontSize(20)
        .text(formatValue(s.value, s.format), x + 12, y + 30, { width: cardW - 24 });
      x += cardW + gap;
    });

    doc.y = y + cardH + 20;
  }

  private async renderChart(doc: PDFKit.PDFDocument, ctx: GenerationContext): Promise<void> {
    if (!ctx.layout.chart || !ctx.dataset.rows.length) return;
    try {
      const png = await renderChartPng(ctx.dataset.rows, ctx.layout.chart);
      const { margins } = doc.page;
      const usable = doc.page.width - margins.left - margins.right;
      if (doc.y > doc.page.height - 320) doc.addPage();
      doc
        .fontSize(14)
        .fillColor(COLORS.text)
        .text(ctx.layout.chart.title ?? 'Chart', margins.left, doc.y);
      doc.moveDown(0.5);
      const imgW = Math.min(usable, 480);
      doc.image(png, margins.left, doc.y, { width: imgW });
      doc.y += (imgW / 2) + 20;
    } catch {
      /* chart is best-effort; never fail the report over it */
    }
  }

  private renderTable(doc: PDFKit.PDFDocument, ctx: GenerationContext): void {
    const columns = ctx.layout.columns;
    if (!columns.length) return;
    const groups = ctx.layout.groupBy ? this.groupRows(ctx) : [{ key: null, rows: this.sortRows(ctx) }];

    const { margins } = doc.page;
    const usable = doc.page.width - margins.left - margins.right;
    const widths = resolveWidths(columns, usable);
    const rowH = 22;

    doc.addPage();
    doc.fontSize(16).fillColor(COLORS.text).text('Data', margins.left, margins.top);
    doc.moveDown(0.5);

    const drawHeader = (): void => {
      const y = doc.y;
      let x = margins.left;
      doc.rect(margins.left, y, usable, rowH).fill(COLORS.primary);
      columns.forEach((c, i) => {
        doc
          .fillColor(COLORS.headerText)
          .fontSize(10)
          .text(c.header, x + 4, y + 6, { width: widths[i] - 8, ellipsis: true });
        x += widths[i];
      });
      doc.y = y + rowH;
    };

    const ensureSpace = (): void => {
      if (doc.y + rowH > doc.page.height - margins.bottom) {
        doc.addPage();
        drawHeader();
      }
    };

    for (const group of groups) {
      if (group.key !== null) {
        ensureSpace();
        doc
          .fillColor(COLORS.text)
          .fontSize(11)
          .text(`${ctx.layout.groupBy}: ${group.key}  (${group.rows.length})`, margins.left, doc.y + 4);
        doc.y += rowH;
      }
      drawHeader();

      group.rows.forEach((row, idx) => {
        ensureSpace();
        const y = doc.y;
        if (idx % 2 === 1) doc.rect(margins.left, y, usable, rowH).fill(COLORS.rowAlt);
        let x = margins.left;
        columns.forEach((c, i) => {
          const align = c.format === 'number' || c.format === 'currency' ? 'right' : 'left';
          doc
            .fillColor(COLORS.text)
            .fontSize(9)
            .text(formatValue(row[c.field], c.format), x + 4, y + 6, {
              width: widths[i] - 8,
              align,
              ellipsis: true,
            });
          x += widths[i];
        });
        doc
          .strokeColor(COLORS.border)
          .lineWidth(0.5)
          .moveTo(margins.left, y + rowH)
          .lineTo(margins.left + usable, y + rowH)
          .stroke();
        doc.y = y + rowH;
      });
    }
  }

  private renderFooters(doc: PDFKit.PDFDocument, ctx: GenerationContext): void {
    const range = doc.bufferedPageRange();
    const total = range.count;
    const stamp = ctx.meta.generatedAt.toISOString();
    for (let i = 0; i < total; i++) {
      doc.switchToPage(range.start + i);
      const { margins, width, height } = doc.page;
      const y = height - margins.bottom + 20;
      doc
        .fontSize(8)
        .fillColor(COLORS.muted)
        .text(stamp, margins.left, y, { width: 200, align: 'left', lineBreak: false });
      doc.text(
        `Page ${i + 1} of ${total}`,
        width - margins.right - 120,
        y,
        { width: 120, align: 'right', lineBreak: false },
      );
    }
  }
}

function resolveWidths(columns: ColumnConfig[], usable: number): number[] {
  const declared = columns.map((c) => c.width ?? 0);
  const sum = declared.reduce((a, b) => a + b, 0);
  if (sum > 0) {
    const scale = usable / sum;
    return declared.map((w) => (w > 0 ? w * scale : usable / columns.length));
  }
  return columns.map(() => usable / columns.length);
}

function formatParam(v: unknown): string {
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  if (typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(v)) return v.slice(0, 10);
  return String(v ?? '');
}
